# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rytai/CamProject/repo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rytai/CamProject/repo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rytai/CamProject/repo/CMakeFiles /home/rytai/CamProject/repo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rytai/CamProject/repo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iovirta_iot

# Build rule for target.
iovirta_iot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iovirta_iot
.PHONY : iovirta_iot

# fast build rule for target.
iovirta_iot/fast:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/build
.PHONY : iovirta_iot/fast

src/conf/conf.o: src/conf/conf.cpp.o

.PHONY : src/conf/conf.o

# target to build an object file
src/conf/conf.cpp.o:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/conf/conf.cpp.o
.PHONY : src/conf/conf.cpp.o

src/conf/conf.i: src/conf/conf.cpp.i

.PHONY : src/conf/conf.i

# target to preprocess a source file
src/conf/conf.cpp.i:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/conf/conf.cpp.i
.PHONY : src/conf/conf.cpp.i

src/conf/conf.s: src/conf/conf.cpp.s

.PHONY : src/conf/conf.s

# target to generate assembly for a file
src/conf/conf.cpp.s:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/conf/conf.cpp.s
.PHONY : src/conf/conf.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/network/fcm_server.o: src/network/fcm_server.cpp.o

.PHONY : src/network/fcm_server.o

# target to build an object file
src/network/fcm_server.cpp.o:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/network/fcm_server.cpp.o
.PHONY : src/network/fcm_server.cpp.o

src/network/fcm_server.i: src/network/fcm_server.cpp.i

.PHONY : src/network/fcm_server.i

# target to preprocess a source file
src/network/fcm_server.cpp.i:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/network/fcm_server.cpp.i
.PHONY : src/network/fcm_server.cpp.i

src/network/fcm_server.s: src/network/fcm_server.cpp.s

.PHONY : src/network/fcm_server.s

# target to generate assembly for a file
src/network/fcm_server.cpp.s:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/network/fcm_server.cpp.s
.PHONY : src/network/fcm_server.cpp.s

src/video/camera.o: src/video/camera.cpp.o

.PHONY : src/video/camera.o

# target to build an object file
src/video/camera.cpp.o:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/video/camera.cpp.o
.PHONY : src/video/camera.cpp.o

src/video/camera.i: src/video/camera.cpp.i

.PHONY : src/video/camera.i

# target to preprocess a source file
src/video/camera.cpp.i:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/video/camera.cpp.i
.PHONY : src/video/camera.cpp.i

src/video/camera.s: src/video/camera.cpp.s

.PHONY : src/video/camera.s

# target to generate assembly for a file
src/video/camera.cpp.s:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/video/camera.cpp.s
.PHONY : src/video/camera.cpp.s

src/video/motion.o: src/video/motion.cpp.o

.PHONY : src/video/motion.o

# target to build an object file
src/video/motion.cpp.o:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/video/motion.cpp.o
.PHONY : src/video/motion.cpp.o

src/video/motion.i: src/video/motion.cpp.i

.PHONY : src/video/motion.i

# target to preprocess a source file
src/video/motion.cpp.i:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/video/motion.cpp.i
.PHONY : src/video/motion.cpp.i

src/video/motion.s: src/video/motion.cpp.s

.PHONY : src/video/motion.s

# target to generate assembly for a file
src/video/motion.cpp.s:
	$(MAKE) -f CMakeFiles/iovirta_iot.dir/build.make CMakeFiles/iovirta_iot.dir/src/video/motion.cpp.s
.PHONY : src/video/motion.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... iovirta_iot"
	@echo "... src/conf/conf.o"
	@echo "... src/conf/conf.i"
	@echo "... src/conf/conf.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network/fcm_server.o"
	@echo "... src/network/fcm_server.i"
	@echo "... src/network/fcm_server.s"
	@echo "... src/video/camera.o"
	@echo "... src/video/camera.i"
	@echo "... src/video/camera.s"
	@echo "... src/video/motion.o"
	@echo "... src/video/motion.i"
	@echo "... src/video/motion.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

